### ISSUE TITLE
ERROR: Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0

### ISSUE THREAD

**Issue by deleteNames** [Lichenwei-Dev/ImagePicker#1]
ERROR: Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
Show in Project Structure dialog
Affected Modules: app

**Comment by Lichenwei-Dev** [comment]
> ERROR: Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
> Show in Project Structure dialog
> Affected Modules: app

**Comment by Lichenwei-Dev** [comment]
> ERROR: Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
> Show in Project Structure dialog
> Affected Modules: app

Hi deleteNames, Thanks for your suggestions.  
PhotoView from Maven,use this in your module level build.gradle:
```
allprojects {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }
}
```

**Comment by Lichenwei-Dev** [comment]
> ERROR: Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
> Show in Project Structure dialog
> Affected Modules: app

> ERROR: Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
> Show in Project Structure dialog
> Affected Modules: app

Hi deleteNames, Thanks for your suggestions.  
PhotoView comes from Maven,you can use this in your module level build.gradle:
```
allprojects {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }
}
```
