### ISSUE TITLE
安卓8.0系统闪退

### ISSUE THREAD

**Issue by xinzhenyong** [Lichenwei-Dev/ImagePicker#10]
报错FATAL EXCEPTION: main
                                                              Process: com.dashixiong, PID: 8302
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dashixiong/com.lcw.library.imagepicker.activity.ImagePickerActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

**Comment by Lichenwei-Dev** [comment]
这个和你项目中配置有关系，当设置了Activity为透明时，在8.0系统后是不能设置orientation属性的。
