### ISSUE TITLE
有直接打开相机的代码吗

### ISSUE THREAD

**Issue by q735510971** [Lichenwei-Dev/ImagePicker#11]
因为产品要求打开弹出选择相机和相册,我看到代码中ImagePickerActivity的showCamera()方法,楼主有没有考虑 加一个回调呢

**Comment by Lichenwei-Dev** [comment]
> 因为产品要求打开弹出选择相机和相册,我看到代码中ImagePickerActivity的showCamera()方法,楼主有没有考虑 加一个回调呢

你的建议是想提供一个自定义打开相机的方法供外部实现吗？

**Comment by FynnJason** [comment]
> > 因为产品要求打开弹出选择相机和相册,我看到代码中ImagePickerActivity的showCamera()方法,楼主有没有考虑 加一个回调呢
> 
> 你的建议是想提供一个自定义打开相机的方法供外部实现吗？



> > 因为产品要求打开弹出选择相机和相册,我看到代码中ImagePickerActivity的showCamera()方法,楼主有没有考虑 加一个回调呢
> 
> 你的建议是想提供一个自定义打开相机的方法供外部实现吗？

他的意思就是直接打开相机拍照进行回调，这个功能其实都不用本库来实现了，直接intent相机即可，在onactivityresult回调就好了 2333

**Comment by Lichenwei-Dev** [comment]
> > > 因为产品要求打开弹出选择相机和相册,我看到代码中ImagePickerActivity的showCamera()方法,楼主有没有考虑 加一个回调呢
> > 
> > 
> > 你的建议是想提供一个自定义打开相机的方法供外部实现吗？
> 
> > > 因为产品要求打开弹出选择相机和相册,我看到代码中ImagePickerActivity的showCamera()方法,楼主有没有考虑 加一个回调呢
> > 
> > 
> > 你的建议是想提供一个自定义打开相机的方法供外部实现吗？
> 
> 他的意思就是直接打开相机拍照进行回调，这个功能其实都不用本库来实现了，直接intent相机即可，在onactivityresult回调就好了 2333

嗯对，可以的，如果需要图片选择功能可以用本库，然后关闭拍照选项就可以了，外部自己用intent来实现。
