### ISSUE TITLE
能判断是否为GIF图吗？

### ISSUE THREAD

**Issue by FynnJason** [Lichenwei-Dev/ImagePicker#12]
在列表中，GIF图会有标识吗？有单独只显示GIF的功能吗？在选择图片时，能检测是否为GIF图吗？

**Comment by Lichenwei-Dev** [comment]
有的，如果是gif图片在图片列表页会显示gif的图标
单独显示gif图片这个目前还没有支持，如果你有需要你可以提个pr或者等我完善~
