### ISSUE TITLE
Android Q Not Support

### ISSUE THREAD

**Issue by VayneKaso** [Lichenwei-Dev/ImagePicker#16]

**Comment by Lichenwei-Dev** [comment]
目前手上没有对应的Android Q设备，等有了设备会第一时间设配。

**Comment by xxMinGW** [comment]
Android Q还没有适配吗？ 建议大佬适配一下Android Q吧。。。

**Comment by Lichenwei-Dev** [comment]
> Android Q还没有适配吗？ 建议大佬适配一下Android Q吧。。。

目前这个库在Android Q系统上跑，好像没有发现什么问题，如果有什么问题可以反馈给我哈。
