### ISSUE TITLE
关于裁剪框

### ISSUE THREAD

**Issue by chipssss** [Lichenwei-Dev/ImagePicker#17]
请问裁剪框大小可以支持修改吗？默认裁剪框在部分手机显示太小。谢谢🙏

**Comment by VayneKaso** [comment]
这个带裁剪功能吗？？请问你怎么调用的。

**Comment by chipssss** [comment]
> 这个带裁剪功能吗？？请问你怎么调用的。

ImagePicker.getInstance().setCrop(true);

**Comment by JustinChiang123** [comment]
我怎么没看到ImagePicker.getInstance().setCrop(true);，，，请问我们用的同一个东西吗？
