### ISSUE TITLE
fragment   里面选择图片没有提供start方法

### ISSUE THREAD

**Issue by a615696671** [Lichenwei-Dev/ImagePicker#19]
/**
     * 启动
     *
     * @param activity
     */
public void start(AppCompatActivity activity, int requestCode) {
        Intent intent = new Intent(activity, ImagePickerActivity.class);
        activity.startActivityForResult(intent, requestCode);
    }

not fragment  

    public void start(Fragment fragment, int requestCode) {
        Intent intent = new Intent(fragment.getContext(), ImagePickerActivity.class);
        fragment.startActivityForResult(intent, requestCode);
    }

**Comment by Lichenwei-Dev** [comment]
> /**
> * 启动
> *
> * @param activity
> */
> public void start(AppCompatActivity activity, int requestCode) {
> Intent intent = new Intent(activity, ImagePickerActivity.class);
> activity.startActivityForResult(intent, requestCode);
> }
> 
> not fragment
> 
> ```
> public void start(Fragment fragment, int requestCode) {
>     Intent intent = new Intent(fragment.getContext(), ImagePickerActivity.class);
>     fragment.startActivityForResult(intent, requestCode);
> }
> ```

你可以获取到承载这个Fragment的宿主Activity，然后进行后续的操作，比如：getActivity().startActivityForResult(intent, requestCode);
