### ISSUE TITLE
crash  ！！！！！

### ISSUE THREAD

**Issue by a615696671** [Lichenwei-Dev/ImagePicker#20]
ImagePickerActivity mRecyclerView.addOnScrollListener（）
当相册中没有视频的时候updateImageTime()；
 int position = mGridLayoutManager.findFirstVisibleItemPosition();   源码中RecyclerView.NO_POSITION=-1; 
 /**
     * 更新时间
     */
    private void updateImageTime() {
        int position = mGridLayoutManager.findFirstVisibleItemPosition();
        if(position!=-1){  //加入判断
            //mGridLayoutManager.findFirstVisibleItemPosition() 没有的时候返回-1  这里做判断操作
            MediaFile mediaFile = mImagePickerAdapter.getMediaFile(position);
            if (mediaFile != null) {
                if (mTvImageTime.getVisibility() != View.VISIBLE) {
                    mTvImageTime.setVisibility(View.VISIBLE);
                }
                String time = Utils.getImageTime(mediaFile.getDateToken());
                mTvImageTime.setText(time);
                showImageTime();
                mMyHandler.removeCallbacks(mHideRunnable);
                mMyHandler.postDelayed(mHideRunnable, 1500);
            }
        }
    }

**Comment by Lichenwei-Dev** [comment]
感谢你的反馈，问题已经在最新版修复。
