### ISSUE TITLE
设置图片选择历史记录会出现Bug

### ISSUE THREAD

**Issue by AndroidBreathing** [Lichenwei-Dev/ImagePicker#21]
在设置.setImagePaths时 外层list已经被清空 
log日志也是为空 
但进入图片选择页的时候 还是会有上次选中的图片
时而出现 ！

**Comment by Lichenwei-Dev** [comment]
> 在设置.setImagePaths时 外层list已经被清空
> log日志也是为空
> 但进入图片选择页的时候 还是会有上次选中的图片
> 时而出现 ！

可以提供下复现的路径吗，我这里测试，没有发现这个问题。

**Comment by AndroidBreathing** [comment]
嗯  晚一些回复给您

**Comment by AndroidBreathing** [comment]
@Lichenwei-Dev  嗯 晚一些回复给您
