### ISSUE TITLE
能否设置默认的一个图片文件夹

### ISSUE THREAD

**Issue by yueshaolong** [Lichenwei-Dev/ImagePicker#22]

**Comment by Lichenwei-Dev** [comment]
是否可以具体描述一下需求？

**Comment by yueshaolong** [comment]
在选择图片页面最上边应该有个相册名字，点击那个名字可以选择其它其它相册；一般都是默认选择全部照片，能否加一个默认选中自己app设置的一个相册
![Uploading Screenshot_2019-11-07-13-31-34.jpg…]()
