### ISSUE TITLE
相机的路径

### ISSUE THREAD

**Issue by 214024475** [Lichenwei-Dev/ImagePicker#24]
Demo里面没有给出相机的入口  只能从相册里面选择

**Comment by Lichenwei-Dev** [comment]
> Demo里面没有给出相机的入口 只能从相册里面选择

调用ImagePick的时候是否设置有showCamera(true)？

**Comment by 214024475** [comment]
&nbsp;感谢提出的建议，建议你可以看一下https://github.com/cl-6666/theSelector/tree/masterImagePicker.getInstance().startCamera(MainActivity.this, code); 调用系统相册showCamera(true)//控制相册里面是否显示拍照按钮





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李晨玮"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午3:25
收件人:&nbsp;"Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com&gt;;
抄送:&nbsp;"无名✨"<214024475@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lichenwei-Dev/ImagePicker] 相机的路径 (#24)



 
Demo里面没有给出相机的入口 只能从相册里面选择
  
调用ImagePick的时候是否设置有showCamera(true)？
