### ISSUE TITLE
图片预览无法加载

### ISSUE THREAD

**Issue by HaobinXu** [Lichenwei-Dev/ImagePicker#26]
1.我用依赖方式集成：implementation 'com.lcw.library:imagepicker:2.2.7'，图片加载器也是用Glide，版本和你demo中用的一样，是4.9.0。但是你的demo可以预览图片，我项目中就是不行……按照你demo的方式跳转的。
2.我用module方式集成，跳转到预览页会直接报错，定位到是ImagePickerAdapter第168行数组越界了。

所以我很纳闷，明明你的demo在我手机上运行没有问题，但是我自己的项目运行有问题。我的手机是一加7 plus，android Q系统。是不是因为我的targetSdkVersion是29的原因？你的demo是27

**Comment by Lichenwei-Dev** [comment]
> 1.我用依赖方式集成：implementation 'com.lcw.library:imagepicker:2.2.7'，图片加载器也是用Glide，版本和你demo中用的一样，是4.9.0。但是你的demo可以预览图片，我项目中就是不行……按照你demo的方式跳转的。
> 2.我用module方式集成，跳转到预览页会直接报错，定位到是ImagePickerAdapter第168行数组越界了。
> 
> 所以我很纳闷，明明你的demo在我手机上运行没有问题，但是我自己的项目运行有问题。我的手机是一加7 plus，android Q系统。是不是因为我的targetSdkVersion是29的原因？你的demo是27

你好，这个和targetSdkVersion是没有关系的，我刚才看了下ImagePickerAdapter的168行，那里是用来区分是否是gif图片，取图片路径的最后一个“.”位置，下个版本我会做个容错处理，感谢你的反馈。

**Comment by Riant** [comment]
@HaobinXu 我也是图片没法预览了，小图、大图都只显示占位图片。

--你最后解决了吗？--

好吧，看来是这个原因 https://github.com/Lichenwei-Dev/ImagePicker/issues/41
