### ISSUE TITLE
fragment中调用start只能传activity？

### ISSUE THREAD

**Issue by anzhuojinjie** [Lichenwei-Dev/ImagePicker#27]
ImagePicker.getInstance()
                                .setTitle("标题")//设置标题
                                .showCamera(true)//设置是否显示拍照按钮
                                .showImage(true)//设置是否展示图片
                                .showVideo(false)//设置是否展示视频
                                .setSingleType(true)//设置图片视频不能同时选择
//                                .setMaxCount(9)//设置最大选择图片数目(默认为1，单选)
//                                .setImagePaths(mImageList)//保存上一次选择图片的状态，如果不需要可以忽略
                                .setImageLoader(new GlideImagePickerLoader())//设置自定义图片加载器
                                .start(getActivity(), 0);//REQEST_SELECT_IMAGES_CODE为Intent调用的requestCode

start只能传activity？这样无法回调fragment的onActivityResult   有咩有好的解决方案

**Comment by Lichenwei-Dev** [comment]
嗯，对，目前来讲是只能传activity，你需要在承载fragment的activity里去接收回调，如果你觉得这样通讯起来很麻烦，可以通过eventbus来解决该问题。
