### ISSUE TITLE
点击相机的时候,回调判断有误

### ISSUE THREAD

**Issue by peng093** [Lichenwei-Dev/ImagePicker#6]
具体表现是拍照后,选择确定没有反应,照片也没有回调,我看了下源码,发现问题所在
`/**
     * 拍照回调
     *
     * @param requestCode
     * @param resultCode
     * @param data
     */
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == RESULT_OK) {// 0,拍照返回resultCode=0,而RESULT_OK=-1,导致回调失败
            if (requestCode == REQUEST_CODE_CAPTURE) {
                //通知媒体库刷新
                sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.parse("file://" + mFilePath)));
                //添加到选中集合
                SelectionManager.getInstance().addImageToSelectList(mFilePath);

                List<String> list = new ArrayList<>(SelectionManager.getInstance().getSelectPaths());
                Intent intent = new Intent();
                intent.putStringArrayListExtra(ImagePicker.EXTRA_SELECT_IMAGES, (ArrayList<String>) list);
                setResult(RESULT_OK, intent);
                finish();
            }

            if (requestCode == REQUEST_SELECT_IMAGES_CODE) {
                commitSelection();
            }
        }
    }`
// `另外,建议可以自定文字,比如改成英文,顶部的标题可以自定义,但是右上角的选中文字不可以自定义`

**Comment by Lichenwei-Dev** [comment]
拍照成功后点击确认按钮返回的RESULT_OK为什么会是0呢？
这是Activity源码里的：
    /** Standard activity result: operation canceled. */
    public static final int RESULT_CANCELED    = 0;
    /** Standard activity result: operation succeeded. */
    public static final int RESULT_OK           = -1;
请问你是什么手机？

**Comment by weiyoupeng** [comment]
谷歌手机 Xl




------------------ 原始邮件 ------------------
发件人: "李晨玮"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 下午2:33
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com>;
抄送: "2394668226"<2394668226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Lichenwei-Dev/ImagePicker] 点击相机的时候,回调判断有误 (#6)




拍照成功后点击确认按钮返回的RESULT_OK为什么会是0呢？
 这是Activity源码里的：
 /** Standard activity result: operation canceled. /
 public static final int RESULT_CANCELED    = 0;
 /* Standard activity result: operation succeeded. */
 public static final int RESULT_OK           = -1;
 请问你是什么手机？

**Comment by Lichenwei-Dev** [comment]
> 谷歌手机 Xl

找了几把谷歌手机测试，确实发现该问题，和国产手机返回值不一样，待修复这个问题。

**Comment by weiyoupeng** [comment]
如果是谷歌手机加一下判断来区分吧------------------ 原始邮件 ------------------
发件人: "李晨玮"<notifications@github.com>
发送时间: 2019年5月16日(星期四) 下午4:48
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com>;
抄送: "weiyoupeng"<2394668226@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Lichenwei-Dev/ImagePicker] 点击相机的时候,回调判断有误 (#6)


 
谷歌手机 Xl
  
找了几把谷歌手机测试，确实发现该问题，和国产手机返回值不一样，待修复这个问题。
 
&mdash;

**Comment by FynnJason** [comment]
小米8有同样的问题，拍照后没有任何反应，直接回到了选择界面 @Lichenwei-Dev

**Comment by Lichenwei-Dev** [comment]
不应该有这个问题，我自己的手机就是米8，你运行下项目里的demo试试？


 
---原始邮件---
发件人: "FynnJason"<notifications@github.com&gt;
发送时间: 2019年9月2日(星期一) 上午9:40
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"李晨玮"<lichenwei.me@foxmail.com&gt;;
主题: Re: [Lichenwei-Dev/ImagePicker] 点击相机的时候,回调判断有误 (#6)



小米8有同样的问题，拍照后没有任何反应，直接回到了选择界面 @Lichenwei-Dev

**Comment by FynnJason** [comment]
我觉得你可以这样试试能不能复现，安装App，启动图片选择，然后拍照，确认，我就是这么做的，确实很容易复现出来。刚才我不知道点了什么，又可以正常拍照了。但是我卸载重装，发现问题又出现了。你需要卸载了重新安装试试。 @Lichenwei-Dev

**Comment by Lichenwei-Dev** [comment]
好嘞，感谢你的反馈，我稍后排查下问题。




------------------ 原始邮件 ------------------
发件人: "FynnJason"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 上午9:49
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com>;
抄送: "李晨玮"<lichenwei.me@foxmail.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Lichenwei-Dev/ImagePicker] 点击相机的时候,回调判断有误 (#6)




我觉得你可以这样试试能不能复现，安装App，启动图片选择，然后拍照，确认，我就是这么做的，确实很容易复现出来。刚才我不知道点了什么，又可以正常拍照了。但是我卸载重装，发现问题又出现了。你需要卸载了重新安装试试。 @Lichenwei-Dev

**Comment by FynnJason** [comment]
@Lichenwei-Dev Demo也一样复现出来了，运行Demo，然后拍照，确认后就回到图片选择页面了，没有任何反应了。

**Comment by FynnJason** [comment]
@Lichenwei-Dev requestCode = 2 ，resultCode = 0 ，最神奇的是，不知道什么操作，重新运行demo，又正常了。然后我卸载了重试，又复现

**Comment by Lichenwei-Dev** [comment]
可能跟国产的ROM有关系，需要一套兼容方案，哈哈，可以一起研究下～


 
---原始邮件---
发件人: "FynnJason"<notifications@github.com&gt;
发送时间: 2019年9月2日(星期一) 上午10:14
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"李晨玮"<lichenwei.me@foxmail.com&gt;;
主题: Re: [Lichenwei-Dev/ImagePicker] 点击相机的时候,回调判断有误 (#6)



@Lichenwei-Dev requestCode = 2 ，resultCode = 0 ，最神奇的是，不知道什么操作，重新运行demo，又正常了。然后我卸载了重试，又复现

**Comment by Lichenwei-Dev** [comment]
> @Lichenwei-Dev requestCode = 2 ，resultCode = 0 ，最神奇的是，不知道什么操作，重新运行demo，又正常了。然后我卸载了重试，又复现

原因已经查到了，是由于指定MediaStore.EXTRA_OUTPUT的路径导致的 ，具体解决方案这周末我研究下。

**Comment by Lichenwei-Dev** [comment]
问题已经修复，由于权限问题导致的，部分机型上首次申请存储卡读权限并没有对应的把写权限给你，尽管它们归属于同一个组，需要等待下次打开app的时候才生效，目前已经修复这个问题。请更新版本2.2.4




------------------ 原始邮件 ------------------
发件人: "FynnJason"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 上午10:14
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com>;
抄送: "李晨玮"<lichenwei.me@foxmail.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Lichenwei-Dev/ImagePicker] 点击相机的时候,回调判断有误 (#6)




@Lichenwei-Dev requestCode = 2 ，resultCode = 0 ，最神奇的是，不知道什么操作，重新运行demo，又正常了。然后我卸载了重试，又复现

**Comment by Lichenwei-Dev** [comment]
最新版本：2.2.5
