### ISSUE TITLE
设置最大选择图片数目为1，显示拍照按钮，拍完照选择后，下次进来还是选择状态

### ISSUE THREAD

**Issue by xmlxin** [Lichenwei-Dev/ImagePicker#7]
有一个小问题，设置最大选择图片数目为1，显示拍照按钮，拍完照选择后，下次进来还是选择状态。多谢作者提供这么好用的库。

**Comment by Lichenwei-Dev** [comment]
> 有一个小问题，设置最大选择图片数目为1，显示拍照按钮，拍完照选择后，下次进来还是选择状态。多谢作者提供这么好用的库。

感谢反馈，晚上就把这个问题修复。

**Comment by xmlxin** [comment]
多谢作者及时处理问题

**Comment by Lichenwei-Dev** [comment]
> 多谢作者及时处理问题

问题已修复，2.1.3版本。

**Comment by treasuresyi** [comment]
2.2.2，还是没有解决呢？

**Comment by Lichenwei-Dev** [comment]
试试2.2.3版本哈~




------------------ 原始邮件 ------------------
发件人: "Lord"<notifications@github.com>;
发送时间: 2019年8月25日(星期天) 晚上7:02
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com>;
抄送: "李晨玮"<lichenwei.me@foxmail.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Lichenwei-Dev/ImagePicker] 设置最大选择图片数目为1，显示拍照按钮，拍完照选择后，下次进来还是选择状态 (#7)




2.2.2，还是没有解决呢？

**Comment by Lichenwei-Dev** [comment]
> 2.2.2，还是没有解决呢？

2.2.3版本尝试下。

**Comment by treasuresyi** [comment]
好的，谢谢




------------------ 原始邮件 ------------------
发件人: "李晨玮"<notifications@github.com>;
发送时间: 2019年8月25日(星期天) 晚上11:09
收件人: "Lichenwei-Dev/ImagePicker"<ImagePicker@noreply.github.com>;
抄送: "Lord Zeng"<309727767@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Lichenwei-Dev/ImagePicker] 设置最大选择图片数目为1，显示拍照按钮，拍完照选择后，下次进来还是选择状态 (#7)



 
2.2.2，还是没有解决呢？
  
2.2.3版本尝试下。
